name: Contexts
on: [push, workflow_dispatch]
jobs:
  print: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}" # githubコンテキストの参照
      - run: echo "${{ github.run_id }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.workspace }}"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.action }}"
      - run: echo "${{ github.event.pull_request }}"
